In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

查看tensor数据类型

In [ ]:
num = tf.constant([1,2], dtype=tf.int64)    # 常量型
usr_bool = tf.constant([True])              # 布尔型
usr_string = tf.constant("Hello world!")    # 字符型
print(num)

a1 = tf.zeros(3)
a2 = tf.ones([3,3])
a3 = tf.fill([3,3], 3)  # 指定数
print(a1, a2, a3)

In [ ]:
a1 = tf.random.normal([2,2], mean=0, stddev=1)  # 生成正态分布随机数张量，输入参数：维度，均值，标准差
a2 = tf.random.truncated_normal([2,2], mean=0, stddev=1) # 生成截断式正态分布随机数张量，输入参数：维度，均值，标准差，输出数据均在mean±2*stddev之内
print(a1, a2)

In [6]:
# 生成[0,1)内的随机数
rdm = np.random.RandomState(seed=1)     # 定义随机数生成器rdm，使用随机数种子seed=1
usr_random1 = rdm.rand()    # 无输入维度时返回一个常量
usr_random2 = rdm.rand(2, 3) # 返回2行3列的随机数矩阵
print("usr_random1= {} \r\n usr_random2= {}".format(usr_random1, usr_random2))

usr_random1= 0.417022004702574 
 usr_random2= [[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]


In [8]:
# 数组垂直叠加
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
b = np.vstack((a1, a2))
print(b)

[[1 2 3]
 [4 5 6]]


In [21]:
# 范围数组生成，数组拉伸，多数组配对组合
a1, a2 = np.mgrid[1:3:1, 3:6:0.5]
print(a1)
print(a2)

b = np.c_[np.ravel(a1), np.ravel(a2)]   # a1.ravel()执行二维变一维拉伸，np.c_进行组合操作
print(b)

[[1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]]
[[3.  3.5 4.  4.5 5.  5.5]
 [3.  3.5 4.  4.5 5.  5.5]]
[[1.  3. ]
 [1.  3.5]
 [1.  4. ]
 [1.  4.5]
 [1.  5. ]
 [1.  5.5]
 [2.  3. ]
 [2.  3.5]
 [2.  4. ]
 [2.  4.5]
 [2.  5. ]
 [2.  5.5]]


从numpy中导入数据

In [ ]:
a = np.arange(0, 5)
b = tf.convert_to_tensor(a, dtype=tf.int64)
print(a)
print(b)

## 常用函数

#### 张量处理类

In [ ]:
a1 = tf.constant([1,2,3], dtype=tf.float64)
print(a1)
a2 = tf.cast(a1, tf.int64)  # 强制数据类型转换
print(a2)

print(tf.reduce_min(a2), tf.reduce_max(a2)) # 查找张量数据中的最小值和最大值

In [ ]:
a1 = tf.constant([[1,2,3],[2,3,4]])
print(a1)
print(tf.reduce_max(a1, axis=0))    # 按照列查找最大的行
print(tf.reduce_sum(a1,axis=1))     # 按照行计算各列的和

In [29]:
# 张量数据索引
test = np.array([[1, 2, 3],[2, 3, 4],[5, 6, 7], [7, 8, 2]])
print(test)
print(tf.argmax(test, axis=0))  # 按列查找，找到每一列的最大值序列号
print(tf.argmax(test, axis=1))  # 按行查找，找到每一行的最大值序列号

[[1 2 3]
 [2 3 4]
 [5 6 7]
 [7 8 2]]
tf.Tensor([3 3 2], shape=(3,), dtype=int64)
tf.Tensor([2 2 2 1], shape=(4,), dtype=int64)


#### 数学运算类

In [ ]:
a1 = tf.constant([[1,2,3],[1,2,3]])
a2 = tf.constant([[2,3,4],[2,3,4]])
print(tf.add(a1, a2))   # 加
print(tf.subtract(a1, a2))  # 减
print(tf.multiply(a1, a2))  # 乘
print(tf.divide(a1, a1))    # 除

In [ ]:
a1 = tf.fill([1,3], 3.)  # 这里的指定值为3. 小数点是为了生成float32类型数据
print(a1)
print(tf.pow(a1, 3))    # 开三次方根
print(tf.square(a1))    # 平方
print(tf.square(a1))    # 开方

In [ ]:
a = tf.ones([3, 2])     # 3行2列
b = tf.fill([2, 3], 3.) # 2行3列
print(tf.matmul(a, b))  # 矩阵叉乘得6行6列，叉乘的两个矩阵，前者的列数必须和后者的行数相等

#### 网络训练类

In [ ]:
tf.Variable(tf.random.normal([2,2],mean=0,stddev=1))    # 标记可以用于训练修改的权重参数

In [ ]:
# data = tf.data.Dataset.from_tensor_slices((特征数据, 标签数据)) 可以直接输入numpy或者tensor格式的数据
features = tf.constant([[12,13], [15,16], [20,21], [10,11]])    # 特征数据
labels = tf.constant([0, 1, 1, 0])          # 标签
dataset = tf.data.Dataset.from_tensor_slices((features, labels))    # 对应结合
for element in dataset:
    print(element)  # 输出

In [ ]:
with tf.GradientTape() as tape: # 记录上下文微分信息
    w = tf.Variable(tf.constant(3.0))   # 可变参数，初值为3.0
    loss = tf.pow(w, 2) # 损失函数
grad = tape.gradient(loss, w)   # 损失函数对w求导
print(grad)

In [ ]:
# 枚举列表
data = ['one', 'two', 'three']
for i, element in enumerate(data):  # 返回的第一个是序列号，第二个是内容
    print(i, element)

In [2]:
# 条件循环
a = tf.constant([1, 2, 3, 4, 5])
b = tf.constant([0, 1, 3, 4, 5])
c = tf.where(tf.greater(a, b), a, b)    # 如果条件为真返回第一个值，条件假返回第二个值
print(c)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [ ]:
# 独热码
classes = 4     # 标签数
labels = tf.constant([1, 0, 6 ,3])  # 输入标签数据
output = tf.one_hot(labels, depth=classes)  # 独热码转换
print(output)

In [ ]:
# softmax()
y = tf.constant([1.01, 2.02, -1.11])
y_out = tf.nn.softmax(y)
print("data {}, after softmax is {}".format(y, y_out))

In [ ]:
# 跟新参数
w = tf.Variable(4)
w.assign_sub(1)
print(w)